version: '3.8'

services:
  django:
    build: ./setup
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./setup:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  vue:
    build: ./front-leilao
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - vue
