# Generated by Django 4.2.13 on 2024-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default='9.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
