# Generated by Django 4.2.13 on 2024-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0004_item_auction_date_item_category_item_city_item_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
