# Generated by Django 4.2.13 on 2024-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0005_remove_item_description_remove_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Imóvel', 'Imóvel'), ('Veículo', 'Veículo')], max_length=20),
        ),
    ]
