# Generated by Django 4.2.13 on 2024-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0006_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='auction_date',
        ),
    ]
