# Generated by Django 4.2.13 on 2024-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0007_remove_item_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auction_date',
            field=models.DateField(default='2024-07-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='auction_time',
            field=models.TimeField(default='15:30:00'),
            preserve_default=False,
        ),
    ]
