# Generated by Django 4.2.13 on 2024-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0008_item_auction_date_item_auction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='increment_value',
            field=models.DecimalField(decimal_places=2, default='2000.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default='200000.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='increment_value',
            field=models.DecimalField(decimal_places=2, default='400.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default='10000.00', max_digits=10),
            preserve_default=False,
        ),
    ]
