# Generated by Django 4.2.13 on 2024-06-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0010_realestate_bid_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bid_history',
            field=models.JSONField(default=list),
        ),
    ]
